NAME : PAREENITA ATUL SHIRSATH   B.E.A.I.&.D.S.   ROLL.NO : 57

PRN : 221101062

DLL EXPERIMENT NO : 03


In [4]:
import numpy as np
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

# Set seed for reproducibility
tf.random.set_seed(42)
np.random.seed(42)

# Adjusted dataset: linearly related input and target
x_train = np.array([
    [0.1, 0.2],
    [0.3, 0.7],
    [0.4, 0.5],
    [0.9, 0.6]
])

# Adjusted to better match linear patterns
y_train = np.array([
    0.1 * 0.2 + 0.1 + 0.2,    # 0.32
    0.3 * 0.7 + 0.3 + 0.7,    # 1.21
    0.4 * 0.5 + 0.4 + 0.5,    # 1.10
    0.9 * 0.6 + 0.9 + 0.6     # 2.04
])

# Define a simple model (smaller, avoids overfitting)
model = Sequential([
    Dense(8, activation='relu', input_shape=(2,)),
    Dense(4, activation='relu'),
    Dense(1)
])

model.compile(optimizer='adam', loss='mse')

# Function to print weights and biases
def print_weights_and_biases(model, note=""):
    print(f"\nWeights and biases {note}:")
    for i, layer in enumerate(model.layers):
        weights, biases = layer.get_weights()
        print(f"Layer {i+1} weights:\n{weights}")
        print(f"Layer {i+1} biases:\n{biases}")

print_weights_and_biases(model, "before training")

# Train the model (more epochs for better learning)
model.fit(x_train, y_train, epochs=500, verbose=0)

print_weights_and_biases(model, "after training")

# Make predictions
predictions = model.predict(x_train)

# Print predicted vs target values
print("\nPredictions vs Targets:")
for i in range(len(x_train)):
    print(f"Input: {x_train[i]}, Target: {y_train[i]:.2f}, Predicted: {predictions[i][0]:.2f}")



Weights and biases before training:
Layer 1 weights:
[[ 0.59901106 -0.05383408 -0.4362802   0.42319632  0.5578557   0.3527676
   0.5631325   0.01105005]
 [ 0.5268421   0.3442788   0.6246679   0.17209041 -0.69514346  0.19653642
   0.65762126  0.37114716]]
Layer 1 biases:
[0. 0. 0. 0. 0. 0. 0. 0.]
Layer 2 weights:
[[ 0.25377393  0.5929335  -0.07843089  0.3267514 ]
 [ 0.49246854  0.14196962 -0.22040811 -0.6133759 ]
 [-0.08697289  0.2329424  -0.57399017 -0.6421802 ]
 [-0.34535515  0.41102022  0.6347756   0.51362354]
 [ 0.30713946  0.49564236 -0.43863776  0.23663229]
 [-0.00137854  0.56021017 -0.40159976  0.24928409]
 [-0.08901161  0.09524715 -0.28089425 -0.66490936]
 [ 0.2573473   0.48224694 -0.6170491  -0.58231163]]
Layer 2 biases:
[0. 0. 0. 0.]
Layer 3 weights:
[[-0.21868503]
 [ 0.83318317]
 [-1.0336787 ]
 [ 0.6772084 ]]
Layer 3 biases:
[0.]

Weights and biases after training:
Layer 1 weights:
[[ 0.723424    0.18861961 -0.3153277   0.5339235   0.73317367  0.4713406
   0.690629    0.1374